import { config } from "./src/config.js";
import { MaestroBridge } from "./bridge/maestroBridge.js";
import { collectTexts } from "./bai_tap/navigation/homeworkExamEngine.js";
import { detectQuestionUiType } from "./vui_hoc/vuiHocQuestionMatcher.js";
const bridge = new MaestroBridge({ appId: config.appId, deviceId: config.deviceId || undefined });
const opt = process.argv[2];
const r = await bridge.runSteps([{ tapOn: opt }, { waitForAnimationToEnd: { timeout: 800 } }, { tapOn: { id: "exercise_check_button" } }, { waitForAnimationToEnd: { timeout: 1200 } }]);
console.log("submit success:", r.success, r.error || "");
const tree = await bridge.hierarchy();
console.log("uiType:", detectQuestionUiType(tree));
console.log(JSON.stringify(collectTexts(tree), null, 2));
