import { config } from "./src/config.js";
import { MaestroBridge } from "./bridge/maestroBridge.js";
import { collectTexts } from "./bai_tap/navigation/homeworkExamEngine.js";
import { detectQuestionUiType } from "./vui_hoc/vuiHocQuestionMatcher.js";
const bridge = new MaestroBridge({ appId: config.appId, deviceId: config.deviceId || undefined });
const steps = [];
for (let i = 0; i < 8; i++) steps.push({ tapOn: { id: `exercise_sentence_word_${i}`, optional: true } });
steps.push({ tapOn: { id: "exercise_check_button" } }, { waitForAnimationToEnd: { timeout: 1200 } });
const r = await bridge.runSteps(steps);
console.log("success:", r.success, r.error || "");
const tree = await bridge.hierarchy();
console.log("uiType:", detectQuestionUiType(tree));
console.log(JSON.stringify(collectTexts(tree), null, 2));
