# Cấu hình chung cho toàn bộ workspace Maestro.
# Tham khảo: https://maestro.mobile.dev/api-reference/configuration/project-configuration-file
flows:
  - "flows/*.yaml"
  - "flows/login/*.yaml"
  - "flows/vui_hoc/*.yaml"
  - "flows/profile/*.yaml"
  - "flows/bai_tap/*.yaml"
  - "flows/homework/*.yaml"
  - "flows/exercise/*.yaml"
  - "flows/report/*.yaml"
